# PEARSON CORRELATION COEFFICIENT BASED FEATURE SELECTION ALGORITHM

In [2]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = load_wine()
df = pd.DataFrame(data.data, columns = data.feature_names)
df["DEP_F"] = data.target
features = []
features = data.feature_names
features

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [4]:
col = dict()

In [5]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,DEP_F
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [6]:
from sklearn import preprocessing

arr = df.to_numpy()
min_max_scaler= preprocessing.MinMaxScaler()
scaled_arr = min_max_scaler.fit_transform(arr)
data_norm = pd.DataFrame(scaled_arr)
data_norm.drop(data_norm.columns[0], inplace = True, axis = 1)
wine = data_norm.to_numpy()
wine

array([[0.1916996 , 0.57219251, 0.25773196, ..., 0.97069597, 0.56134094,
        0.        ],
       [0.2055336 , 0.4171123 , 0.03092784, ..., 0.78021978, 0.55064194,
        0.        ],
       [0.3201581 , 0.70053476, 0.41237113, ..., 0.6959707 , 0.64693295,
        0.        ],
       ...,
       [0.69960474, 0.48128342, 0.48453608, ..., 0.10622711, 0.39728959,
        1.        ],
       [0.36561265, 0.54010695, 0.48453608, ..., 0.12820513, 0.40085592,
        1.        ],
       [0.66403162, 0.73796791, 0.71649485, ..., 0.12087912, 0.20114123,
        1.        ]])

In [7]:
wine.shape

(178, 13)

In [8]:
graph = data_norm.corr()
graph

,1,2,3,4,5,6,7,8,9,10,11,12,13
1,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011,0.437776
2,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626,-0.049643
3,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597,0.517859
4,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,-0.209179
5,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115,-0.719163
6,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193,-0.847498
7,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385,0.489109
8,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417,-0.499130
9,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100,0.265668
10,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183,-0.617369
11,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761,-0.788230
12,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000,-0.633717
13,0.437776,-0.049643,0.517859,-0.209179,-0.719163,-0.847498,0.489109,-0.499130,0.265668,-0.617369,-0.788230,-0.633717,1.000000

In [9]:
graph = graph.to_numpy()
for i in range(len(graph)):
    graph[i][i] = 0
graph

array([[ 0.        ,  0.16404547,  0.2885004 , -0.0545751 , -0.335167  ,
        -0.41100659,  0.29297713, -0.22074619,  0.24898534, -0.56129569,
        -0.36871043, -0.19201056,  0.4377762 ],
       [ 0.16404547,  0.        ,  0.44336719,  0.28658669,  0.12897954,
         0.11507728,  0.18623045,  0.00965194,  0.25888726, -0.07466689,
         0.00391123,  0.22362626, -0.04964322],
       [ 0.2885004 ,  0.44336719,  0.        , -0.08333309, -0.32111332,
        -0.35136986,  0.36192172, -0.19732684,  0.01873198, -0.27395522,
        -0.27676855, -0.44059693,  0.51785911],
       [-0.0545751 ,  0.28658669, -0.08333309,  0.        ,  0.21440123,
         0.19578377, -0.25629405,  0.23644061,  0.19995001,  0.0553982 ,
         0.06600394,  0.39335085, -0.20917939],
       [-0.335167  ,  0.12897954, -0.32111332,  0.21440123,  0.        ,
         0.8645635 , -0.4499353 ,  0.61241308, -0.05513642,  0.43368134,
         0.69994936,  0.49811488, -0.71916334],
       [-0.41100659,  0.11507728, -0.35136986,  0.19578377,  0.8645635 ,
         0.        , -0.53789961,  0.65269177, -0.1723794 ,  0.54347857,
         0.7871939 ,  0.49419313, -0.84749754],
       [ 0.29297713,  0.18623045,  0.36192172, -0.25629405, -0.4499353 ,
        -0.53789961,  0.        , -0.3658451 ,  0.13905701, -0.26263963,
        -0.5032696 , -0.31138519,  0.48910916],
       [-0.22074619,  0.00965194, -0.19732684,  0.23644061,  0.61241308,
         0.65269177, -0.3658451 ,  0.        , -0.02524993,  0.29554425,
         0.5190671 ,  0.3304167 , -0.49912982],
       [ 0.24898534,  0.25888726,  0.01873198,  0.19995001, -0.05513642,
        -0.1723794 ,  0.13905701, -0.02524993,  0.        , -0.52181319,
        -0.42881494,  0.31610011,  0.26566757],
       [-0.56129569, -0.07466689, -0.27395522,  0.0553982 ,  0.43368134,
         0.54347857, -0.26263963,  0.29554425, -0.52181319,  0.        ,
         0.56546829,  0.23618345, -0.61736921],
       [-0.36871043,  0.00391123, -0.27676855,  0.06600394,  0.69994936,
         0.7871939 , -0.5032696 ,  0.5190671 , -0.42881494,  0.56546829,
         0.        ,  0.31276108, -0.78822959],
       [-0.19201056,  0.22362626, -0.44059693,  0.39335085,  0.49811488,
         0.49419313, -0.31138519,  0.3304167 ,  0.31610011,  0.23618345,
         0.31276108,  0.        , -0.63371678],
       [ 0.4377762 , -0.04964322,  0.51785911, -0.20917939, -0.71916334,
        -0.84749754,  0.48910916, -0.49912982,  0.26566757, -0.61736921,
        -0.78822959, -0.63371678,  0.        ]])

In [10]:
s = np.sum(graph)
threshold = s / ((graph.shape[0] ** 2) - 13)
print(threshold)

0.02547262230625494

In [11]:
for i in range(len(graph)):
    for j in range(len(graph[0])):
        if graph[i][j] < threshold :
            graph[i][j] = 0
graph

array([[0.        , 0.16404547, 0.2885004 , 0.        , 0.        ,
        0.        , 0.29297713, 0.        , 0.24898534, 0.        ,
        0.        , 0.        , 0.4377762 ],
       [0.16404547, 0.        , 0.44336719, 0.28658669, 0.12897954,
        0.11507728, 0.18623045, 0.        , 0.25888726, 0.        ,
        0.        , 0.22362626, 0.        ],
       [0.2885004 , 0.44336719, 0.        , 0.        , 0.        ,
        0.        , 0.36192172, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.51785911],
       [0.        , 0.28658669, 0.        , 0.        , 0.21440123,
        0.19578377, 0.        , 0.23644061, 0.19995001, 0.0553982 ,
        0.06600394, 0.39335085, 0.        ],
       [0.        , 0.12897954, 0.        , 0.21440123, 0.        ,
        0.8645635 , 0.        , 0.61241308, 0.        , 0.43368134,
        0.69994936, 0.49811488, 0.        ],
       [0.        , 0.11507728, 0.        , 0.19578377, 0.8645635 ,
        0.        , 0.        , 0.65269177, 0.        , 0.54347857,
        0.7871939 , 0.49419313, 0.        ],
       [0.29297713, 0.18623045, 0.36192172, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.13905701, 0.        ,
        0.        , 0.        , 0.48910916],
       [0.        , 0.        , 0.        , 0.23644061, 0.61241308,
        0.65269177, 0.        , 0.        , 0.        , 0.29554425,
        0.5190671 , 0.3304167 , 0.        ],
       [0.24898534, 0.25888726, 0.        , 0.19995001, 0.        ,
        0.        , 0.13905701, 0.        , 0.        , 0.        ,
        0.        , 0.31610011, 0.26566757],
       [0.        , 0.        , 0.        , 0.0553982 , 0.43368134,
        0.54347857, 0.        , 0.29554425, 0.        , 0.        ,
        0.56546829, 0.23618345, 0.        ],
       [0.        , 0.        , 0.        , 0.06600394, 0.69994936,
        0.7871939 , 0.        , 0.5190671 , 0.        , 0.56546829,
        0.        , 0.31276108, 0.        ],
       [0.        , 0.22362626, 0.        , 0.39335085, 0.49811488,
        0.49419313, 0.        , 0.3304167 , 0.31610011, 0.23618345,
        0.31276108, 0.        , 0.        ],
       [0.4377762 , 0.        , 0.51785911, 0.        , 0.        ,
        0.        , 0.48910916, 0.        , 0.26566757, 0.        ,
        0.        , 0.        , 0.        ]])

In [12]:
def findNodeImportance(graph):
    imp = []
    imp = graph.sum(axis=0)
    return imp

In [13]:
def selectNode(imp):
    node = np.argmax(imp)
    print("Node removed from graph : ", node)
    return node

In [14]:
def delete_corresponding_edges(node, graph):
    for i in range(len(graph)):
        graph[node][i] = 0
        graph[i][node] = 0
    return graph

In [15]:
nodes = []
while np.sum(graph) != 0:
    important = findNodeImportance(graph)
    node = selectNode(important)
    nodes.append(node)
    graph = delete_corresponding_edges(node, graph)

Node removed from graph :  5
Node removed from graph :  4
Node removed from graph :  11
Node removed from graph :  12
Node removed from graph :  1
Node removed from graph :  10
Node removed from graph :  0
Node removed from graph :  7
Node removed from graph :  6
Node removed from graph :  3

In [16]:
nodes

[5, 4, 11, 12, 1, 10, 0, 7, 6, 3]

In [17]:
nodes.sort()
nodes

[0, 1, 3, 4, 5, 6, 7, 10, 11, 12]

In [23]:
df[features[0]]

0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 178, dtype: float64

In [30]:
nodes

[0, 1, 3, 4, 5, 6, 7, 10, 11, 12]

In [32]:
final_data = df
for i in range(len(features)):
    for j in nodes:
        if i == j:
            break
        elif i < j:
            final_data.drop(features[i], inplace = True, axis = 1)
            i+=1
            break
final_data

,alcohol,malic_acid,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,hue,od280/od315_of_diluted_wines,proline,DEP_F
0,14.23,1.71,15.6,127.0,2.80,3.06,0.28,1.04,3.92,1065.0,0
1,13.20,1.78,11.2,100.0,2.65,2.76,0.26,1.05,3.40,1050.0,0
2,13.16,2.36,18.6,101.0,2.80,3.24,0.30,1.03,3.17,1185.0,0
3,14.37,1.95,16.8,113.0,3.85,3.49,0.24,0.86,3.45,1480.0,0
4,13.24,2.59,21.0,118.0,2.80,2.69,0.39,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,1.68,0.61,0.52,0.64,1.74,740.0,2
174,13.40,3.91,23.0,102.0,1.80,0.75,0.43,0.70,1.56,750.0,2
175,13.27,4.28,20.0,120.0,1.59,0.69,0.43,0.59,1.56,835.0,2
176,13.17,2.59,20.0,120.0,1.65,0.68,0.53,0.60,1.62,840.0,2
177,14.13,4.10,24.5,96.0,2.05,0.76,0.56,0.61,1.60,560.0,2

In [50]:
def intersection(lst1, lst2):
    return list(set(lst1) & set(lst2))

# A = set of attributes
def equivalence_class_util(x, A):
    val = []
    for j in A:
        val.append(x[j])
    return val


# A = set of attributes
def equivalence_class(data, A):
    eq_class = []
    for i, x in enumerate(data.values):
        val = equivalence_class_util(x, A)
    
    found_class = False
    for c in eq_class:
        if(val == equivalence_class_util(data.values[c[0]], A)):
            found_class = True
            c.append(i)
            break
    
    if(not found_class):
        eq_class.append([i])
    return eq_class


# P = set of attributes
# X = set of objects
def len_lower_approximation(data, P, X):
    len_lower_P = 0
    EC = equivalence_class(data, P)
    for x in X:
        for c in EC:
            if((x in c) and (intersection(c, X) == c)):
                len_lower_P += 1
                break
    return len_lower_P;


# P = a subset of attributes
# eq_class_decision = equivalence class of decision attribute
def gamma(data, P, eq_class_Q):
    if(not P):
        return 0
    denom = len(data)
    numer = 0
    
    for qi in eq_class_Q:
        numer += len_lower_approximation(data, P, qi)
        
    return numer / denom


# data should not contain decision attribute column
# features should not contain decision attribute
def QRGA(data, features, decision_attribute):
    reduct = []
    T = []
    
    num_features = len(features)

    eq_class_decision = []
    
    for i, x in enumerate(data.values):
        found_class = False
    for c in eq_class_decision:
        if(decision_attribute[i] == decision_attribute[c[0]]):
            found_class = True
            c.append(i)
            break
    
    if(not found_class):
        eq_class_decision.append([i])
        
    is_cond = True
    while(is_cond):
        T = reduct.copy()
        for x in range(num_features):
            if(x in reduct):
                continue
            tmp = reduct.copy()
            tmp.append(x)
            if(gamma(data, tmp, eq_class_decision) > gamma(data, T, eq_class_decision)):
                T.append(x)
                reduct = T.copy()
        is_cond = gamma(data, reduct, eq_class_decision) > gamma(data, features, eq_class_decision)
    reduct.sort()
    return reduct

In [48]:
decision = df.loc[ :,['DEP_F']]
decision

     DEP_F
0        0
1        0
2        0
3        0
4        0
..     ...
173      2
174      2
175      2
176      2
177      2

[178 rows x 1 columns]

In [53]:
columns = range(13)

In [55]:
reduct = QRGA(data_norm, columns, decision)
reduct

[0]